# Import Libraries

In [11]:
#Import Libraries
import pandas as pd
import numpy as np
import os
# visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

# Import dataframe

In [2]:
#Identify path 
path= '../02 Data/'

In [4]:
#import products
df_health=pd.read_csv(os.path.join(path, 'Original Data','Healthcare_Investments_and_Hospital_Stay.csv'), index_col=False)

In [6]:
df_health.head()

  Location  Time  Hospital_Stay  MRI_Units  CT_Scanners  Hospital_Beds
0      AUS  1992            6.6       1.43        16.71           1.43
1      AUS  1994            6.4       2.36        18.48           2.36
2      AUS  1995            6.5       2.89        20.55           2.89
3      AUS  1996            6.4       2.96        21.95           2.96
4      AUS  1997            6.2       3.53        23.34           3.53

# Data Consistency Check

In [12]:
# shape of dataset
df_health.shape

(518, 6)

In [7]:
# Statistical Summary
df_health.describe ()

              Time  Hospital_Stay   MRI_Units  CT_Scanners  Hospital_Beds
count   518.000000     518.000000  518.000000   518.000000     518.000000
mean   2007.967181       7.140154   10.565502    19.646718      10.565502
std       6.944160       2.566864    8.685570    14.352069       8.685570
min    1990.000000       3.400000    0.100000     1.480000       0.100000
25%    2003.250000       5.800000    4.072500    10.332500       4.072500
50%    2009.000000       6.650000    8.765000    15.375000       8.765000
75%    2014.000000       7.500000   13.877500    26.592500      13.877500
max    2018.000000      32.700000   55.210000   111.490000      55.210000

In [10]:
# checking for column format
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       518 non-null    object
 1   Time           518 non-null    int64
 2   Hospital_Stay  518 non-null    float64
 3   MRI_Units      518 non-null    float64
 4   CT_Scanners    518 non-null    float64
 5   Hospital_Beds  518 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 24.4+ KB

In [13]:
# check for missing values
df_health.isnull().sum()

Location         0
Time             0
Hospital_Stay    0
MRI_Units        0
CT_Scanners      0
Hospital_Beds    0
dtype: int64

In [15]:
# check for duplicates
df_health_dup=df_health[df_health.duplicated()]

In [16]:
df_health_dup

Empty DataFrame
Columns: [Location, Time, Hospital_Stay, MRI_Units, CT_Scanners, Hospital_Beds]
Index: []

In [18]:
# advanced function to search for mixed type data columns
for col in df_health.columns.tolist():
  weird = (df_health[[col]].map(type) != type(df_health[col].iloc[0])).any(axis=1)
  if len(df_health[weird]) > 0:
    print(col)

Time
Hospital_Stay
MRI_Units
CT_Scanners
Hospital_Beds

In [21]:
# checking values for location
df_health['Location'].value_counts(dropna=False)

Location
HUN    29
FIN    28
RUS    25
AUS    23
AUT    23
ITA    22
FRA    21
CAN    20
ISR    19
LTU    19
CZE    19
KOR    18
NLD    18
DEU    18
LUX    17
TUR    17
LVA    16
BEL    16
SVK    16
EST    14
POL    14
IRL    13
USA    13
ISL    12
SVN    12
GBR    12
NZL    11
GRC    10
ESP     9
JPN     7
DNK     4
PRT     3
Name: count, dtype: int64

# Column renaming

In [23]:
# change column name 
df_health.rename(columns={'Hospital_Stay':'hospital_stay'}, inplace=True)

In [28]:
# change column name 
df_health.rename(columns={'MRI_Units':'mri_units'}, inplace=True)

In [25]:
# change column name 
df_health.rename(columns={'CT_Scanners':'ct_scanners'}, inplace=True)

In [29]:
df_health.head()

  Location  Time  hospital_stay  mri_units  ct_scanners  hospital_beds
0      AUS  1992            6.6       1.43        16.71           1.43
1      AUS  1994            6.4       2.36        18.48           2.36
2      AUS  1995            6.5       2.89        20.55           2.89
3      AUS  1996            6.4       2.96        21.95           2.96
4      AUS  1997            6.2       3.53        23.34           3.53

In [26]:
# change column name 
df_health.rename(columns={'Hospital_Beds':'hospital_beds'}, inplace=True)

# export

In [31]:
# exporting cleaned
df_health.to_pickle(os.path.join(path,'Prepared Data','health_cleaned.pkl'))